// This file is auto-generated by openapi-typescript
// Run: pnpm gen:api
// Source: openapi/openapi.json

// Placeholder - will be generated when openapi.json is populated with actual API schema

export interface paths {}
export interface components {}
export interface operations {}
